import {
  Baby,
  Banknote,
  Briefcase,
  Building2,
  Car,
  FileText,
  Gavel,
  Globe,
  HardHat,
  Handshake,
  HeartPulse,
  Home,
  Landmark,
  LayoutDashboard,
  Leaf,
  type LucideIcon,
  Laptop,
  PawPrint,
  Plane,
  Scale,
  Shield,
  ShieldAlert,
  ShieldCheck,
  ShoppingCart,
  ScrollText,
  Sprout,
  Stethoscope,
  Trophy,
  Users,
  Vote,
} from "lucide-react";

// Regras por palavra-chave, mais específicas primeiro — cada ícone reflete o conteúdo real
// da área (não é decoração), pra dar escaneabilidade visual na lista de 31 capítulos.
const REGRAS: [string, LucideIcon][] = [
  ["Perante Tribunais", Gavel],
  ["Atividades Jurídicas Avulsas", FileText],
  ["Compliance", ShieldCheck],
  ["Gestão Jurídica", LayoutDashboard],
  ["Administrativo", Building2],
  ["Aeronáutico", Plane],
  ["Agrário", Sprout],
  ["Ambiental", Leaf],
  ["Animalista", PawPrint],
  ["Bancário", Banknote],
  ["Desportivo", Trophy],
  ["Digital", Laptop],
  ["Eleitoral", Vote],
  ["Empresarial", Briefcase],
  ["Imobiliário", Home],
  ["Internacional", Globe],
  ["Militar", Shield],
  ["Municipalista", Building2],
  ["Penal", ShieldAlert],
  ["Previdenciário", HeartPulse],
  ["Tributário", Landmark],
  ["Criança e do Adolescente", Baby],
  ["Saúde", Stethoscope],
  ["Sucessões", ScrollText],
  ["Família", Users],
  ["Trânsito", Car],
  ["Consumidor", ShoppingCart],
  ["Trabalho", HardHat],
  ["Juizados Especiais", Scale],
  ["Mediação", Handshake],
  ["Civil", Scale],
];

export function getAreaIcon(area: string): LucideIcon {
  const encontrada = REGRAS.find(([chave]) => area.includes(chave));
  return encontrada ? encontrada[1] : Scale;
}
